### ISSUE TITLE
STXXL Not Found During cmake

### ISSUE THREAD

**Issue by Terry1004** [mdimura/sparsehc-dm#1]
I tried the commands provided by the readme file on ubuntu 18.04.
![screenshot_version](https://user-images.githubusercontent.com/21012146/40570977-59881988-60c3-11e8-9a9b-283c8daf9b25.png)
Then I ran as in the example:
`sudo apt-get install libboost-graph-dev libstxxl-dev libstxxl1`
![screenshot_install1](https://user-images.githubusercontent.com/21012146/40571024-39f38ed0-60c4-11e8-88fd-fdf0358fd437.png)
As hinted by the error notes, I ran the following instead:
`sudo apt-get install libboost-graph-dev libstxxl-dev libstxxl1v5`
It seemed to be successful, and the following is printed (I have previously installed libboost-all-dev):
![screenshot_install2](https://user-images.githubusercontent.com/21012146/40571263-58c80724-60c8-11e8-8e60-df08f4ff9d61.png)
So I proceeded with
```
git clone https://github.com/Burning-Daylight/sparsehc-dm.git sparsehc-dm
cd sparsehc-dm
mkdir build
cd build
cmake ..
```
Then I encountered the error suggesting that STXXL could not be found by find_package:
![image](https://user-images.githubusercontent.com/21012146/40571276-a68558ae-60c8-11e8-87d6-8b1618998921.png)
However, I am not very familiar with C, and not sure how to resolve the problem.

**Comment by mdimura** [comment]
It seems, there is a bug in the STXXL package on Ubuntu 18.04. You could try to install stxxl from sources as suggested in the ["Notes for Linux Distribution Package Maintainers" section](http://stxxl.org/tags/1.4.1/install_unix.html#install_unix_library):
```
git clone http://github.com/stxxl/stxxl.git
mkdir stxxl/release; cd stxxl/release
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC_LIBS=ON
make -j4
sudo make install
```
This should put all the necessary CMake configuration files in proper places.

**Comment by Terry1004** [comment]
Thank you so much! This method works well and `cmake ..` runs successfully.
However, another error occurred when I proceeded to `make` saying
```
Scanning dependencies of target python_init
[  0%] Built target python_init
Scanning dependencies of target sparsehc_dm
[  5%] Building CXX object CMakeFiles/sparsehc_dm.dir/python/sparsehc-dm_python.cpp.o
[ 10%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/averagecluster.cpp.o
[ 15%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/cluster.cpp.o
[ 20%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/common.cpp.o
[ 25%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/completecluster.cpp.o
[ 30%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/dendrogram.cpp.o
[ 35%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/inmatrix.cpp.o
[ 40%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/matrix.cpp.o
[ 45%] Building CXX object CMakeFiles/sparsehc_dm.dir/src/singlecluster.cpp.o
[ 50%] Linking CXX shared library sparsehc_dm.so
/usr/bin/x86_64-linux-gnu-ld: /usr/local/lib/libstxxl.a(syscall_file.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN5stxxl9singletonINS_5statsELb1EE8instanceE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/sparsehc_dm.dir/build.make:305: recipe for target 'sparsehc_dm.so' failed
make[2]: *** [sparsehc_dm.so] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/sparsehc_dm.dir/all' failed
make[1]: *** [CMakeFiles/sparsehc_dm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
By the way, due to the removal of boost::python::numeric API in boost 1.65, only installation of boost library with version before 1.65 can ensure successful execution of `make`.

**Comment by mdimura** [comment]
I am not sure, what is really the problem, but you can try reinstalling the stxxl with 
`set(CMAKE_POSITION_INDEPENDENT_CODE ON)`. You will need to add this line to stxxl/CMakeLists.txt and recompile/reinstall the stxxl.
```
...
# the STXXL project
project(stxxl)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
...
```

**Comment by Terry1004** [comment]
It works! Thank you again.

**Comment by june30** [comment]
I also have similar problems. Although terry1004 solve the problem, my computer still has problem.

![image](https://user-images.githubusercontent.com/11401913/56353545-8dd22580-620c-11e9-8b77-ed6d86c044c6.png)

'sudo cmake' was successful, but 'sudo make' had an error.

I try to reinstall the stxxl with set(CMAKE_POSITION_INDEPENDENT_CODE ON) as you recommended. However, there was still same problem. Can I get some advice?  I don't know c++ language well.
